server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    use-actual-param-name: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto
  mapper-locations: classpath*:mapper/**/*Mapper.xml

oss:
  accessKey: c8rBYMwnVssCCEnfMiHZx6Jo0g-_630xIZMDi2Nj
  secretKey: 4f4_3Pb0svNkbcGYHzBD6o1tIMZllSA7cxS7qhFz
  bucket: wen-vue-blog
  url: http://r9cmuofj0.hn-bkt.clouddn.com/